[profile.default]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200

# Directories
src = "src"
out = "out"
test = "test"
cache_path = "cache"
libs = ["lib"]

# Remappings
remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "forge-std/=lib/forge-std/src/",
  "account-abstraction/=lib/account-abstraction/contracts/"
]
